spring.application.name=utility-billing-system

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/utility_billing}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.docker.compose.enabled=false
spring.docker.compose.lifecycle-management=none

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=${JWT_SECRET:replace-this-with-a-very-long-secret-key-for-utility-billing-system}
jwt.expiration=${JWT_EXPIRATION:86400000}
