spring.application.name=utility-billing-system

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/utility_billing}
spring.datasource.username=${DB_USERNAME:polo}
spring.datasource.password=${DB_PASSWORD:#nelprox92}
spring.docker.compose.enabled=false
spring.docker.compose.lifecycle-management=none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never

springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=${JWT_SECRET:replace-this-with-a-very-long-secret-key-for-utility-billing-system}
jwt.expiration=${JWT_EXPIRATION:86400000}
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:nelsonprox92@gmail.com}
spring.mail.password=${MAIL_PASSWORD:zzto wzjk yxlp ocan}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
management.health.mail.enabled=false
app.notifications.email.enabled=${APP_NOTIFICATIONS_EMAIL_ENABLED:true}
app.notifications.email.from=${APP_NOTIFICATIONS_EMAIL_FROM:${spring.mail.username:}}
app.notifications.reminder.enabled=${APP_NOTIFICATIONS_REMINDER_ENABLED:true}
app.notifications.reminder.days-before=${APP_NOTIFICATIONS_REMINDER_DAYS_BEFORE:3}
app.notifications.reminder.cron=${APP_NOTIFICATIONS_REMINDER_CRON:0 25 16 * * *}
app.seed.admin.enabled=${APP_SEED_ADMIN_ENABLED:true}
app.seed.admin.full-name=${APP_SEED_ADMIN_FULL_NAME:System Administrator}
app.seed.admin.email=${APP_SEED_ADMIN_EMAIL:admin@utility.rw}
app.seed.admin.phone-number=${APP_SEED_ADMIN_PHONE:0788000000}
app.seed.admin.password=${APP_SEED_ADMIN_PASSWORD:password123}
